spring:
  datasource:
    url: jdbc:mysql://localhost:3306/xnr?serverTimezone=GMT%2b8
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: 123456
  redis:
    host: localhost
    port: 6379
    lettuce:
      pool:
        max-active: 8
        max-wait: -1ms
        min-idle: 0
        max-idle: 8
#  mvc:
#    static-path-pattern: /**
  resources:
    static-locations: file:src/main/resources/
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.jlwl.xnr.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
server:
  port: 8080
  servlet:
    context-path: /xnr

logging:
  level:
    com.jlwl.xnr.controller: DEBUG